name       : pychess
version    : 0.99.4
release    : 3
source     :
    - https://github.com/pychess/pychess/releases/download/0.99.4/pychess-0.99.4.tar.gz : 2e773f5ccf8b6610e7c5831957db737cb4db242c02fc1aa58a65a456a6be0960
license    : GPL-3.0-or-later
component  : games.strategy
summary    : PyChess - a free, pleasant, chess game for the Linux desktop that does
    everything you require from an advanced chess client.
description: |
    PyChess is a chess client for playing and analyzing chess games. It is intended to be usable both for those totally new to chess as well as advanced users who want to use a computer to further enhance their play.

    PyChess has a builtin python chess engine and auto-detects most popular chess engines (Stockfish, Rybka, Houdini, Shredder, GNU Chess, Crafty, Fruit, and many more). These engines are available as opponents, and are used to provide hints and analysis. PyChess also shows analysis from opening books and Gaviota end-game tablebases.

    When you get sick of playing computer players you can login to FICS (the Free Internet Chess Server) and play against people all over the world. PyChess has a built-in Timeseal client, so you won't lose clock time during a game due to lag. PyChess also has pre-move support, which means you can make (or start making) a move before your opponent has made their move.
rundeps    :
    - gnome-icon-theme
    - gstreamer-1.0-plugins-base
    - librsvg
    - python3-cairo
    - python3-gobject
    - python-pexpect
    - python-psutil
    - python-sqlalchemy
build      : |
    %python3_setup
install    : |
    %python3_install

    rm $installdir/usr/share/pixmaps/pychess.svg
    ln -s ../icons/hicolor/scalable/apps/pychess.svg $installdir/usr/share/pixmaps/pychess.svg
