name       : pychess
version    : 1.0.3
release    : 11
source     :
    - https://github.com/pychess/pychess/releases/download/1.0.3/PyChess-1.0.3.tar.gz : 7938fd945edfa7cd235446193bcc10704ad40a310f5c97a76d3673563ac56dfd
homepage   : https://pychess.github.io/
license    : GPL-3.0-or-later
component  : games.strategy
summary    : PyChess - a free, pleasant, chess game for the Linux desktop that does everything you require from an advanced chess client
description: |
    PyChess is a chess client for playing and analyzing chess games. It is intended to be usable both for those totally new to chess as well as advanced users who want to use a computer to further enhance their play. PyChess has a builtin python chess engine and auto-detects most popular chess engines (Stockfish, Rybka, Houdini, Shredder, GNU Chess, Crafty, Fruit, and many more). These engines are available as opponents, and are used to provide hints and analysis. PyChess also shows analysis from opening books and Gaviota end-game tablebases. When you get sick of playing computer players you can login to FICS (the Free Internet Chess Server) and play against people all over the world. PyChess has a built-in Timeseal client, so you won't lose clock time during a game due to lag. PyChess also has pre-move support, which means you can make (or start making) a move before your opponent has made their move.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
    - gstreamer-1.0-plugins-base
    - librsvg
    - python-pexpect
    - python-psutil
    - python-sqlalchemy
    - xorg-server-xvfb
rundeps    :
    - gnome-icon-theme
    - gstreamer-1.0-plugins-base
    - libgtksourceview3
    - librsvg
    - python-gobject
    - python-pexpect
    - python-psutil
    - python-sqlalchemy
    - python-websockets
install    : |
    # Needs X for some reason and our macros do not work with a prefix command.
    xvfb-run python3 setup.py install --root="%installroot%"

    rm $installdir/usr/share/pixmaps/pychess.svg
    ln -s ../icons/hicolor/scalable/apps/pychess.svg $installdir/usr/share/pixmaps/pychess.svg
